version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=auth_test
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
    volumes:
      - .:/var/www
    ports:
      - "8001:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auth_test
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - C:/program1/table/auth_test.sql:/docker-entrypoint-initdb.d/auth_test.sql

volumes:
  db_data:
